import { Inter } from "next/font/google"; // Import Inter font
import "./globals.css";

const inter = Inter({
  variable: "--font-inter", // Set variable name
  subsets: ["latin"], // Ensure Latin subset is used
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
        <body className={`${inter.variable} antialiased`}>
          {children}
        </body>
    </html>
  );
}
